server:
  port: 9200
  
  
#服务的名称
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://192.168.216.128:9411/
#配置采样百分比
  sleuth:
    sampler:
      probability: 1
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      profile: dev
      label: master



#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        exclude: "*"


spring:
  rabbitmq:
    host: 192.168.216.131
    port: 5672
    username: guest
    password: guest
